# path
PATH:
  root_dir: "/home/wx/project/now_project/iocr_trainning"
  data_dir:  "/home/wx/data/iocr_training/ocr/"
  pretrain_model_path: ""
  result_dir: "/home/wx/dump_results/iocr_training"
  expeiment_name: "merge"

S1:
  name: DB
S2:
  name: CRNN
  alphabet: "VAT"
  imgH: 32 

ShareConv:
  name: Resnet50
  FPN: True

Connect:
  name: SimpleROI

E2E:
  params:

Dataset:
  name: pretrain_invoice

EvalVis:
  vis_batch_size : 1

Trainer:

  device: 0  
  load_pretrain_model: True
  epochs : 600
  eval_epoch : 2
  train_batch_size : 2
  tran_loader_workers: 1
  log_print_freq : 10
  val_batch_size : 1

  optimizer: 
    name: SGD
    # optimizer
    lr: 0.0007
    momentum: 0.9
    weight_decay: 0.0001

  scheculer:
    step_size: 3
    gamma: 0.1

