# path
PATH:
  root_dir: "/home/wx/project/now_project/iocr_trainning"
  data_dir:  "/home/wx/data/iocr_training/ocr/"
  pretrain_model_path: ""
  result_dir: "/home/wx/dump_results/iocr_training"
  expeiment_name: "merge_08_31"
S1:
  name: DB
S2:
  name: CRNN
  alphabet: "VAT"
  imgH: 32 

ShareConv:
  name: resnet50_fpn
  FPN: True

Connect:
  name: QuadROI

E2E:
  params:

Dataset:
  name: pretrain_invoice
  root: /home/wx/data/iocr_training/syn6000invoice
  split: data_full
  train_batch_size : 2
  val_batch_size: 1
  resize_h: 1024
  resize_w: 2048
  val_size: 1000

EvalVis:
  metric_items: ['val_acc','train_acc','train_mean_iou','val_mean_iou']

Train:

  device: 0  
  load_pretrain_model: False
  epochs : 600
  eval_epoch : 2
  log_print_freq : 10
  i_batch_eval_freq: 5000

  optimizer: 
    name: Adam
    lr: 0.00005
    beta1: 0.5

  scheculer:
    step_size: 3
    gamma: 0.1

